export const descriptions = {
    apimonitor: "Web-app that allows users to test their API's. User's are given the ability to use custom headers, body's, verbs, etc... Allows users to save API settings in the cloud for easy use anywhere, or the ability to save their settings in local storage for local use. Guest Credentials: user: \"guest\" | pass: \"guest\"",
    quickbudgettool: "Quick Budget Tool is exactly that! A tool designed to quickly estimate the average cost for someone to move to any given state and display the data in an easy-to-read format. The tool was later adapted to calculate many standardized budget types.",
    mikesframeservice: "Project built for client. Serves as a landing page for a local vehicle frame shop and increased the conversion rate for new potential customers significantly. Website built to client's vision. Started as a full-stack app later optimized to frontend only for increased performance.",
    algoExample: "Visualizer and education resource for many popular algorithms and programming concepts. Originally inspired by other resources providing unhelpful explanations, nuance, and complications for algorithms such as TimSort. Algo Example’s goal is to give a simple and intuitive explanation for these concepts."
};

export const aboutMeDescriptions = {
    personalHistory: "Hello, I am Joshua Bergman. Thank you for taking the time to look over my site. A little about myself: I am from Minnesota, a few of my interests include guitar, cars, and almost anything involving computers. I have been involved in computers and programming for as long as I can remember. As a child I started off my interest by wanting to be like my father; the “Computer Guy”. (Systems Architect) During this time I began programming by creating and editing mods for Minecraft. This naturally transitioned to learning Java (language Minecraft was written in) where I used it to make programs to do my math homework.",
    workAndSchool: "Given my passion for technology I decided on studying computer science at Metropolitan State University when I got the opportunity to make a website for an industrial caster business. Since then I have been doing similar work on a contract basis, where I have gotten the opportunity to work in B2B and B2C environments. The majority of this work has been in cooperation with smaller businesses and the main focus is simple web apps that serve as a landing page, information page, and/or small web store."
};